### ISSUE TITLE
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--use_adap_threshold', 'True']

### ISSUE THREAD

**Issue by Sunt-ing** [raymin0223/fast_robust_early_exit#12]
Hi, is the arg use_adap_threshold that appeared in readme and shell scripts supported by the python script? I got the following errors:

```
Traceback (most recent call last):
  File "/local/scratch/f/xiaoze/fast_robust_early_exit/run_summarization.py", line 571, in <module>
    model_args, data_args, training_args, additional_args = parser.parse_args_into_dataclasses()
  File "/local/scratch/e/xiaoze/miniconda3/envs/free/lib/python3.10/site-packages/transformers/hf_argparser.py", line 341, in parse_args_into_dataclasses
    raise ValueError(f"Some specified arguments are not used by the HfArgumentParser: {remaining_args}")
ValueError: Some specified arguments are not used by the HfArgumentParser: ['--use_adap_threshold', 'True']
```

**Comment by Sunt-ing** [comment]
I use a separate conda environment to install the dependencies in requirements.txt and to run the code.

**Comment by raymin0223** [comment]
Hi @Sunt-ing, sorry for the bugs and late reply.
It looks like a typo in our README.md and scripts files, `use_adapt_threshold` is correct. 
Thanks for pointing out this error!
https://github.com/raymin0223/fast_robust_early_exit/blob/fa85e8b339251726aea54b12bdbce3fe74162336/util/additional_args.py#L85

**Comment by Sunt-ing** [comment]
Thanks for your reply! btw, how can I set a dataset limit? currently, it takes a long time to run a dataset.

**Comment by raymin0223** [comment]
If you mean long training time, the simplest way will be reducing `num_training_epochs`. 
If you want to maintain the num_epochs and reduce the training sample numbers, you can set different arguments for `load_dataset`. For example, `dataset = load_dataset({data_path}, split="train[:10%]")` -- I'm not sure if this is correct, and it could not be straightforward to apply this in our python files (e.g., `run_summarization.py`).

**Comment by Sunt-ing** [comment]
Thanks for the reply!
