### ISSUE TITLE
Question: How much GPU time did you spend on finetuning?

### ISSUE THREAD

**Issue by Sunt-ing** [raymin0223/fast_robust_early_exit#15]
Hi, I noticed your training configurations in the paper and I'm interested in the computational resources you spent on fine-tuning. Thanks for your help!

**Comment by raymin0223** [comment]
Sorry, I missed this issue.

We normally used 2 or 4 A6000 GPUs for each experiment. And we set the steps to about 2 days!

**Comment by Sunt-ing** [comment]
Thanks for your reply!
