### ISSUE TITLE
adaptive threshold estimation

### ISSUE THREAD

**Issue by cool-xiang** [raymin0223/fast_robust_early_exit#16]
Thank you very much for your wonderful project! Regarding the adaptive threshold estimation here, in my actual testing, the threshold obtained remained unchanged. When tested on the BIG PATENT dataset, the threshold remained constant at 0.9 for the first 100 samples instead of adaptive transformation as described in the paper. May I ask if there was a problem with my testing? Thank you very much!
"
self.decoder.bmm_model.fit(X, Y)
self.decoder.bmm_threshold = self.decoder.bmm_model.predict_proba(0.3, 0.9)
"
self.decoder.bmm_threshold, this variable remains constant at 0.9 in my test.

**Comment by raymin0223** [comment]
Hi @cool-xiang,

sorry for the late reply. That's somewhat weird.
Could you share the script file? I assumed that you add `--use_adapt_threshold=True`.

Also, can you check intermediate outputs inside `predict_proba` method if it is still changed but eventually becomes 0.9?

**Comment by raymin0223** [comment]
Let me know if you have further questions!!

**Comment by cool-xiang** [comment]
it's ok now! thank you very much!!
