### ISSUE TITLE
Cannot Run it

### ISSUE THREAD

**Issue by zhengkid** [raymin0223/fast_robust_early_exit#2]
I have followed your instructions to run the codes, but I failed to run them. There are no errors but it just cannot work well. For example, there are no outputs and no changes in GPU consumption. Can you help me figure it out?

**Comment by raymin0223** [comment]
Hi @zhengkid,

Sorry for the late reply. Could you provide more details on this?
Did you correctly run `pip install -r requirements.txt`? Oops, and I find a typo, you have to run `bash run_[TASK_NAME]_[DATASET_NAME].sh`
